var isNorth, thisLat, thisLng, declin, compDangle, dispDeclin; function Setup() { SetImperialSelect(); Calculate(); Convert(); SetNumeric(); SetAnimFrame() }
function Calculate(f = !1) {
    isValid = !0; var k = parseCheck("_txtLat", "Latitude", 10, 90); if (isValid) {
        var v = Get32nds(null, "ddDiamInches", "ddDiamFrac"), r = $("rbHemiNorth").checked, w = false, n = $("cbSqGnom").checked, b = v / 2, h = k * RAD, E = Math.sin(h), a = n ? b / Math.cos(h) - b : 0, F = 3.75 * RAD, p = $("cnvsDial"), u = 3 * v; p.width = u + 6; b *= 3; var e = p.width / 2, D = b + Math.sin(h) * b, l = 3 * a; p.height = n ? D + l + 16 : D + 16; a = p.getContext("2d"); a.save(); a.translate(0, 2 + l); var m = RAD270 + h, q = RAD270 - h; a.beginPath(); if (n) {
            a.arc(e, b, b, RAD180 - h, RAD270 -
                h, !1); var d = e + Math.cos(RAD270 - h) * b; var c = b + Math.sin(RAD270 - h) * b; a.moveTo(d, c); a.lineTo(e, -l); d = e + Math.cos(RAD270 + h) * b; a.lineTo(d, c); a.arc(e, b, b, RAD270 + h, h, !1)
        } else a.arc(e, b, b, RAD180 - h, h, !1); a.lineTo(e, b); d = e + Math.cos(RAD180 - h) * b; c = b + Math.sin(RAD180 - h) * b; a.lineTo(d, c); a.strokeStyle = w ? "#677" : "#000"; a.stroke(); w && (a.fillStyle = a.createPattern($("imgMarble"), "repeat"), a.fill()); a.beginPath(); a.moveTo(e, n ? -l : 0); a.lineTo(e, b); d = e + Math.cos(q) * b; c = b + Math.sin(q) * b; a.lineTo(d, c); a.moveTo(e, b); d = e + Math.cos(m) *
            b; c = b + Math.sin(m) * b; a.lineTo(d, c); n = u / 50; a.font = n + "px Verdana"; a.textBaseline = "middle"; a.textAlign = "center"; a.fillStyle = "#000"; u = .05 * b; l = .7 * b; var y = l + 2 * n, z = l + n, A = .84 * b, B = .9 * b; a.textAlign = "center"; a.textBaseline = "middle"; for (var g, t = 1; 24 > t; t++) {
                var C = t / 4; var x = Math.atan(Math.tan(t * F) * E); d = m + x; g = Math.cos(d); c = Math.sin(d); 0 === t % 4 ? (a.moveTo(e + g * u, b + c * u), a.lineTo(e + g * l, b + c * l), a.moveTo(e + g * y, b + c * y), a.save(), a.translate(e + g * z, b + c * z), a.rotate(RAD90 + d), a.fillText(r ? C : 12 - C, 0, 0), a.restore()) : 0 === t % 2 ? a.moveTo(e +
                    g * A, b + c * A) : a.moveTo(e + g * B, b + c * B); d = e + g * b; c = b + c * b; a.lineTo(d, c); d = q - x; g = Math.cos(d); c = Math.sin(d); 0 === t % 4 ? (a.moveTo(e + g * u, b + c * u), a.lineTo(e + g * l, b + c * l), a.moveTo(e + g * y, b + c * y), a.save(), a.translate(e + g * z, b + c * z), a.rotate(RAD90 + d), a.fillText(r ? 12 - C : C, 0, 0), a.restore()) : 0 === t % 2 ? a.moveTo(e + g * A, b + c * A) : a.moveTo(e + g * B, b + c * B); d = e + g * b; c = b + c * b; a.lineTo(d, c)
            } a.strokeStyle = w ? "#444" : "#000"; a.stroke(); x = Math.atan(Math.tan(24 * F) * E); d = m + x; g = Math.cos(d); c = Math.sin(d); a.textBaseline = "bottom"; a.save(); a.translate(e + g * l, b +
                c * l); a.rotate(RAD90 + d); a.textAlign = "right"; a.fillText(" 6 ", 0, 0); a.restore(); a.save(); a.translate(e + .6 * g * b, b + .6 * c * b); a.rotate(d); a.font = 1.2 * n + "px Verdana"; a.fillText(r ? "PM" : "AM", 0, 0); a.restore(); d = q - x; g = Math.cos(d); c = Math.sin(d); a.save(); a.translate(e + g * l, b + c * l); a.rotate(RAD90 + d); a.textAlign = "left"; a.fillText(" 6 ", 0, 0); a.restore(); a.save(); a.translate(e + .6 * g * b, b + .6 * c * b); a.rotate(RAD180 + d); a.font = 1.2 * n + "px Verdana"; a.fillText(r ? "AM" : "PM", 0, 0); a.restore(); d = e + Math.cos(m) * (b - 10); c = b + Math.sin(m) * (b -
                    10); a.font = "12px Verdana"; a.save(); a.textAlign = "right"; a.translate(d, c); a.rotate(m); a.fillText("True " + (r ? "North" : "South") + " \u2192", 0, 0); a.restore(); d = e + .45 * Math.cos(m) * b; c = b + .45 * Math.sin(m) * b; a.save(); a.textAlign = "center"; a.translate(d, c); a.rotate(m); a.fillText("aarushmagic.com", 0, 0); a.restore(); d = e + Math.cos(q) * (b - 10); c = b + Math.sin(q) * (b - 10); a.save(); a.textAlign = "left"; a.translate(d, c); a.rotate(-m); a.fillText("\u2190 True " + (r ? "North" : "South"), 0, 0); a.restore(); d = e + .45 * Math.cos(q) * b; c = b + .45 * Math.sin(q) *
                        b; a.save(); a.textAlign = "center"; a.translate(d, c); a.rotate(-m); a.fillText("aarushmagic.com", 0, 0); a.restore(); w = 16 / Math.tan(h) + 20; d = e + Math.cos(q) * w; c = b + Math.sin(q) * w; a.save(); a.translate(d, c); a.rotate(-m); a.fillText(k + "\u00b0", 0, 0); a.restore(); a.restore(); a.textAlign = "left"; a.font = "14px Verdana"; a.textBaseline = "top"; a.fillText("Latitude " + k + "\u00b0 " + (r ? "North" : "South"), 2, 0); f && (a.fillText("Longitude " + Math.abs(RoundTo(thisLng, 2)) + "\u00b0 " + (0 < thisLng ? "East" : "West"), 2, 24), a.fillText("Compass " + RoundTo(compDangle,
                            1) + "\u00b0", 2, 48)); a.font = "14px Verdana"; a.textAlign = "center"; a.textBaseline = "bottom"; a.fillStyle = "#00f"; p.title = _GetPageFit(p.width, p.height); $("rngLat").value = k; $("rngDiam").value = v
    }
} function rngLat_Change(f) { $("_txtLat").value = f.value; Calculate() } function rngDiam_Change(f) { Bind(null, "ddDiamInches", "ddDiamFrac", f.value); Calculate() }
function Convert() { isValid = !0; var f = parseCheck("txtDeg", "Degrees", 10, 90), k = parseCheck("txtMin", "Minutes", 0, 60), v = parseCheck("txtSec", "Seconds", 0, 60); if (isValid) { var r = f + k / 60 + v / 3600; $("spnConvert").innerHTML = f + "&deg; " + k + '" ' + v + "' = " + RoundTo(r, 3) + "&deg;" } } function CallAnim() { requestAnimFrame(function () { Calculate() }) } var marker;

